"""fix server defaults and timezone on all models

Revision ID: 3c97235fa47a
Revises: bbecd63e0870
Create Date: 2026-06-11 22:55:08.758295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c97235fa47a'
down_revision: Union[str, Sequence[str], None] = 'bbecd63e0870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
